cc_library(
    name = "core_converter_lib",
    srcs = [
        "lightmappert.cpp",
        "rtsmappert.cpp",
    ],
    hdrs = [
        "lightmappert.h",
        "rtsmappert.h",
    ],
    visibility = [
        "//core_mapper:__pkg__",
        "//core_messages:__pkg__",
        "//core_ros:__pkg__",
    ],
    deps = [
        "//boardnet:boardnet_lib",
        "//core_messages",
    ],
)
